<?php /*

This file contains internal information for the Zacky Installer.
Do NOT change. Removing it might prevent you from using the installer 
on this installation in the future.

---
QlpoOTFBWSZTWc+D+E4AAJlfgEAQQId/8CHwDRC/79+7MAEZUBqZEZGRtTU0THooGjJoaHqep5QwGgNAABpoNANAGganqaRig09TQMjagAGhkAX4nlufQ6xqnqapVhDn+4s4mQBxJWSqFFVEoFOGHAjKpHwk7W2GFx0dEwQRJO6YLBBAxNiwTqXGUMDgR3u2Qror4P2q1cFOhYh9WdZdz7YmR+60lsEQ9hUMbBsHXNrSoI9jUMjNmukaBFawQCmS7h6b7UA5NmQPRT4GivSPLshfWr4AUqxDih2yGHIlSeRifsvazOcLMEuH7MCLb74t0Dx05ojD26FjKx5tRKK6aVWJ+Vi601haxdzMCEYAFru31406lo5p2560AQuovtnnisTEnRiCq4HupoyIM4vrpXgLm71Nl0ORbKqiDQxh1JrhxckZotaFMXmryyH+LuSKcKEhnwfwnA==

...

*/
